server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: proximity-service
  profiles:
    default: test
  logging:
    level:
      root: DEBUG
      org.springframework.web: DEBUG
      com.viv.proximity: DEBUG


  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2s

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    consumer:
      group-id: proximity-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    listener:
      ack-mode: manual

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus

  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: ${spring.application.name}

  tracing:
    sampling:
      probability: 1.0

  otlp:
    tracing:
      endpoint: ${MANAGEMENT_OTLP_TRACING_ENDPOINT:http://jaeger:4318/v1/traces}


  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${MANAGEMENT_OPENTELEMETRY_TRACING_EXPORT_OTLP_ENDPOINT:http://jaeger:4318/v1/traces}