version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_db
    ports:
      - "3306:3306"

  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: order_db
    ports:
      - "5432:5432"