create table short_urls (
    id bigint generated by default as identity primary key,
    original_url varchar(2048) not null,
    short_code varchar(32) not null,
    status varchar(16) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    expires_at timestamp with time zone null,
    last_accessed_at timestamp with time zone null,
    redirect_count bigint not null,
    version bigint not null,
    constraint uk_short_urls_short_code unique (short_code)
);

create index idx_short_urls_status on short_urls (status);
create index idx_short_urls_expires_at on short_urls (expires_at);
