package com.viv.business.event;

public enum BusinessEventType {

    BUSINESS_CREATED,

    BUSINESS_UPDATED,

    BUSINESS_ACTIVATED,

    BUSINESS_DEACTIVATED,

    BUSINESS_SUSPENDED,

    BUSINESS_LOCATION_CREATED,

    BUSINESS_LOCATION_UPDATED,

    BUSINESS_LOCATION_DEACTIVATED
}