server:
  port: 8080

app:
  seed:
    locations: true
    
spring:
  application:
    name: location-service
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.viv.location.model
        spring.json.value.default.type: com.viv.location.model.LocationUpdatedEvent

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics